// ═══════════════════════════════════════════
//   Fetches real YouTube tutorial IDs for exercises that lack one and emits
//   src/data/exercise-videos.js  ({ exId: 'videoId' }).
//
//   The API key is read from the YT_API_KEY environment variable and is NEVER
//   written into the output or committed — this runs offline, and only the
//   resulting static id map ships to the browser.
//
//   Usage:
//     YT_API_KEY=xxx node tools/import-youtube.mjs [--limit N] [--dry]
//
//   QUOTA: search.list costs 100 units/query; the default daily quota is
//   10,000 units = 100 lookups/day. The run is therefore resumable — already
//   mapped exercises are skipped, so you can run it daily until complete.
// ═══════════════════════════════════════════
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dir = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dir, '../src/data/exercise-videos.js');

const KEY = process.env.YT_API_KEY;
const args = process.argv.slice(2);
const dry = args.includes('--dry');
const limIdx = args.indexOf('--limit');
const LIMIT = limIdx >= 0 ? parseInt(args[limIdx + 1], 10) : 90;   // stay under 10k units

if (!KEY && !dry) {
  console.error('Missing YT_API_KEY.\n  YT_API_KEY=xxx node tools/import-youtube.mjs --limit 90');
  process.exit(1);
}

const { EXERCISES } = await import('../src/data/exercises.js');
const { PROGRAMS } = await import('../src/data/programs.js');
const { EXERCISE_ANIM } = await import('../src/data/exercise-anim.js');

// Exercises that actually surface in the app get their videos first — quota is
// ~90 lookups/day, so spending it on movements nobody sees would be a waste.
const inPrograms = new Set();
for (const p of PROGRAMS) for (const s of p.sessions) for (const e of s.exercises) inPrograms.add(e.id);

// Resume from whatever we already have.
let existing = {};
if (existsSync(OUT)) {
  try { ({ EXERCISE_VIDEOS: existing } = await import(OUT + '?t=' + Date.now())); }
  catch { existing = {}; }
}

// Priority: curated staples first (they show up most), then library, then
// workout-guide additions. Skip anything that already has a video.
const pending = Object.entries(EXERCISES)
  .filter(([id, ex]) => !ex.youtubeId?.trim() && !existing[id] && ex.name)
  .sort(([a, ea], [b, eb]) => {
    // 1) used by a Program  2) has an animation (shown on the Body Map)
    // 3) curated before bulk-imported  4) name
    const rank = (id) => {
      if (inPrograms.has(id)) return 0;
      if (EXERCISE_ANIM[id]) return 1;
      return /^(fx_|wg_)/.test(id) ? 3 : 2;
    };
    return rank(a) - rank(b) || (ea.name || '').localeCompare(eb.name || '');
  });

console.log(`already mapped: ${Object.keys(existing).length}`);
console.log(`still missing:  ${pending.length}`);
console.log(`this run:       ${Math.min(LIMIT, pending.length)} lookups (~${Math.min(LIMIT, pending.length) * 100} quota units)`);
if (dry) {
  console.log('\n--dry: first 10 that would be fetched:');
  pending.slice(0, 10).forEach(([id, ex]) => console.log(`  ${id} → "${ex.name} proper form technique"`));
  process.exit(0);
}

const sleep = (ms) => new Promise(r => setTimeout(r, ms));

async function search(name) {
  const q = encodeURIComponent(`${name} proper form technique how to`);
  const url = `https://www.googleapis.com/youtube/v3/search?part=snippet&type=video`
    + `&maxResults=1&videoEmbeddable=true&videoSyndicated=true&safeSearch=strict`
    + `&relevanceLanguage=en&q=${q}&key=${KEY}`;
  const res = await fetch(url);
  if (res.status === 403) {
    const body = await res.text();
    throw new Error(`QUOTA/AUTH (403): ${body.slice(0, 300)}`);
  }
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const json = await res.json();
  return json.items?.[0]?.id?.videoId || null;
}

const out = { ...existing };
let added = 0, missed = 0;
for (const [id, ex] of pending.slice(0, LIMIT)) {
  try {
    const vid = await search(ex.name);
    if (vid) { out[id] = vid; added++; console.log(`  ✓ ${id} → ${vid}  (${ex.name})`); }
    else { missed++; console.log(`  · ${id} — no result (${ex.name})`); }
  } catch (e) {
    console.error(`  ! stopping: ${e.message}`);
    break;
  }
  await sleep(120);   // be polite
}

const keys = Object.keys(out).sort();
const sorted = {};
for (const k of keys) sorted[k] = out[k];

writeFileSync(OUT, `// ═══════════════════════════════════════════
//   FITNESS FORGE — Exercise video tutorials
//   GENERATED by tools/import-youtube.mjs — do not edit by hand.
//
//   exerciseId → YouTube video id, resolved via the YouTube Data API at
//   generation time. No API key ships to the browser; only these ids do.
//   Videos are embedded via youtube-nocookie and remain the property of their
//   respective creators — nothing is rehosted.
// ═══════════════════════════════════════════

export const EXERCISE_VIDEOS = ${JSON.stringify(sorted, null, 0)};
`);

console.log(`\nadded ${added}, no result ${missed}`);
console.log(`total mapped: ${keys.length} → wrote ${OUT}`);
const left = pending.length - added - missed;
if (left > 0) console.log(`${left} still missing — run again tomorrow (quota resets daily).`);
