// ═══════════════════════════════════════════
//   Verifies every exercise video id actually resolves, using YouTube's
//   PUBLIC oEmbed endpoint — no API key, no quota.
//
//   Catches two failure modes:
//     • dead      — the video id 404s (deleted, private, or never existed)
//     • mismatch  — the video resolves but its title describes a different
//                   piece of equipment than the exercise (e.g. "Barbell
//                   Shrugs" pointing at a dumbbell video)
//
//   Usage:
//     node tools/verify-videos.mjs           # report only
//     node tools/verify-videos.mjs --fix     # clear bad ids so the exercise
//                                            # falls back to the search card
// ═══════════════════════════════════════════
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dir = dirname(fileURLToPath(import.meta.url));
const fix = process.argv.includes('--fix');
const { EXERCISES } = await import('../src/data/exercises.js');
const { EXERCISE_VIDEOS } = await import('../src/data/exercise-videos.js');

// Equipment words that must not contradict each other between name and title.
const GEAR = ['barbell', 'dumbbell', 'cable', 'machine', 'kettlebell', 'band', 'smith'];
const gearOf = (s) => GEAR.filter(g => new RegExp(`\\b${g}`, 'i').test(s));

const targets = [];
for (const [id, ex] of Object.entries(EXERCISES)) {
  const vid = (ex.youtubeId || '').trim() || EXERCISE_VIDEOS[id];
  if (vid) targets.push({ id, vid, name: ex.name, curated: !!(ex.youtubeId || '').trim() });
}
console.log(`checking ${targets.length} video ids via oEmbed (no key needed)…\n`);

const dead = [], mismatch = [], ok = [];
for (const t of targets) {
  try {
    const r = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${t.vid}&format=json`);
    if (r.status !== 200) { dead.push(t); }
    else {
      const { title } = await r.json();
      t.title = title || '';
      const want = gearOf(t.name), got = gearOf(t.title);
      // Flag only a clear contradiction: the name names gear, the title names
      // different gear. A title that simply omits the gear word is fine.
      if (want.length && got.length && !want.some(w => got.includes(w))) mismatch.push(t);
      else ok.push(t);
    }
  } catch { dead.push(t); }
  await new Promise(r => setTimeout(r, 50));
}

console.log(`alive & consistent : ${ok.length}`);
console.log(`DEAD (404)         : ${dead.length}`);
console.log(`WRONG EQUIPMENT    : ${mismatch.length}`);
if (dead.length) { console.log('\nDead:'); dead.forEach(d => console.log(`  ✗ ${d.id} (${d.name}) → ${d.vid}`)); }
if (mismatch.length) { console.log('\nWrong equipment:'); mismatch.forEach(m => console.log(`  ⚠ ${m.id} (${m.name}) → "${m.title}"`)); }

if (!fix) { console.log('\n(run with --fix to clear the bad ids)'); process.exit(0); }

const bad = new Set([...dead, ...mismatch].map(t => t.id));
// Clear curated ids in exercises.js
let src = readFileSync(resolve(__dir, '../src/data/exercises.js'), 'utf8');
let cleared = 0;
for (const t of [...dead, ...mismatch]) {
  if (!t.curated) continue;
  const re = new RegExp(`(youtubeId:\\s*)'${t.vid}'`, 'g');
  if (re.test(src)) { src = src.replace(re, "$1''"); cleared++; }
}
writeFileSync(resolve(__dir, '../src/data/exercises.js'), src);

// Drop bad ids from the generated map
const kept = {};
for (const [id, vid] of Object.entries(EXERCISE_VIDEOS)) if (!bad.has(id)) kept[id] = vid;
writeFileSync(resolve(__dir, '../src/data/exercise-videos.js'),
  `// GENERATED by tools/import-youtube.mjs, pruned by tools/verify-videos.mjs.\nexport const EXERCISE_VIDEOS = ${JSON.stringify(kept, null, 0)};\n`);

console.log(`\ncleared ${cleared} curated ids; generated map now holds ${Object.keys(kept).length}.`);
console.log('Those exercises now fall back to the "Watch a tutorial" search card.');
