// ═══════════════════════════════════════════
//   Verifies every exercise video id actually resolves, using YouTube's
//   PUBLIC oEmbed endpoint — no API key, no quota.
//
//   Catches two failure modes:
//     • dead      — the video id 404s (deleted, private, or never existed)
//     • mismatch  — the video resolves but its title describes a different
//                   piece of equipment than the exercise (e.g. "Barbell
//                   Shrugs" pointing at a dumbbell video)
//
//   Run this after every tools/resolve-youtube.mjs pass \u2014 ids rot.
//
//   Usage:
//     node tools/verify-videos.mjs           # report only
//     node tools/verify-videos.mjs --fix     # clear bad ids so the exercise
//                                            # falls back to the search card
// ═══════════════════════════════════════════
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dir = dirname(fileURLToPath(import.meta.url));
const fix = process.argv.includes('--fix');
const { EXERCISES } = await import('../src/data/exercises.js');
const { EXERCISE_VIDEOS } = await import('../src/data/exercise-videos.js');

// Equipment words that must not contradict each other between name and title.
const GEAR = ['barbell', 'dumbbell', 'cable', 'machine', 'kettlebell', 'band', 'smith'];
const gearOf = (s) => GEAR.filter(g => new RegExp(`\\b${g}`, 'i').test(s));

const targets = [];
for (const [id, ex] of Object.entries(EXERCISES)) {
  const vid = (ex.youtubeId || '').trim() || EXERCISE_VIDEOS[id];
  if (vid) targets.push({ id, vid, name: ex.name, curated: !!(ex.youtubeId || '').trim() });
}
console.log(`checking ${targets.length} video ids via oEmbed (no key needed)…\n`);

const dead = [], mismatch = [], ok = [], unreachable = [];
// Only a definitive HTTP status may condemn an id. A network error means we
// could not ask — an unthrottled run once reported working media as broken,
// and --fix would have wiped it. Retry, then report as unreachable and skip.
for (const t of targets) {
  let verdict = null;
  for (let attempt = 0; attempt < 3 && !verdict; attempt++) {
    try {
      const r = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${t.vid}&format=json`);
      if (r.status === 200) {
        const { title } = await r.json();
        t.title = title || '';
        const want = gearOf(t.name), got = gearOf(t.title);
        // Flag only a clear contradiction: the name names gear, the title names
        // different gear. A title that simply omits the gear word is fine.
        verdict = (want.length && got.length && !want.some(w => got.includes(w))) ? mismatch : ok;
      } else if (r.status === 404 || r.status === 401 || r.status === 403) {
        verdict = dead;           // definitively gone / not embeddable
      } else if (attempt === 2) {
        t.why = 'HTTP ' + r.status;
        verdict = unreachable;    // 5xx, throttling — not evidence of a dead id
      }
    } catch (e) {
      if (attempt === 2) { t.why = e.message; verdict = unreachable; }
    }
    if (!verdict) await new Promise(r => setTimeout(r, 800 * (attempt + 1)));
  }
  verdict.push(t);
  await new Promise(r => setTimeout(r, 60));
}

console.log(`alive & consistent : ${ok.length}`);
console.log(`UNREACHABLE (skipped): ${unreachable.length}`);
console.log(`DEAD (404)         : ${dead.length}`);
console.log(`WRONG EQUIPMENT    : ${mismatch.length}`);
if (dead.length) { console.log('\nDead:'); dead.forEach(d => console.log(`  ✗ ${d.id} (${d.name}) → ${d.vid}`)); }
if (mismatch.length) { console.log('\nWrong equipment:'); mismatch.forEach(m => console.log(`  ⚠ ${m.id} (${m.name}) → "${m.title}"`)); }

if (!fix) { console.log('\n(run with --fix to clear the bad ids)'); process.exit(0); }

const bad = new Set([...dead, ...mismatch].map(t => t.id));
// Clear curated ids in exercises.js
let src = readFileSync(resolve(__dir, '../src/data/exercises.js'), 'utf8');
let cleared = 0;
for (const t of [...dead, ...mismatch]) {
  if (!t.curated) continue;
  const re = new RegExp(`(youtubeId:\\s*)'${t.vid}'`, 'g');
  if (re.test(src)) { src = src.replace(re, "$1''"); cleared++; }
}
writeFileSync(resolve(__dir, '../src/data/exercises.js'), src);

// Drop bad ids from the generated map
const kept = {};
for (const [id, vid] of Object.entries(EXERCISE_VIDEOS)) if (!bad.has(id)) kept[id] = vid;
const sorted = Object.fromEntries(Object.keys(kept).sort().map(k => [k, kept[k]]));
writeFileSync(resolve(__dir, '../src/data/exercise-videos.js'),
  `// \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550
//   FITNESS FORGE \u2014 Exercise \u2192 YouTube tutorial ids
//   GENERATED by tools/resolve-youtube.mjs, pruned by tools/verify-videos.mjs.
//   Do not edit by hand.
//
//   Ids only \u2014 no video is hosted or redistributed; the app embeds them via
//   youtube-nocookie. ${Object.keys(sorted).length} exercises mapped.
// \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550

export const EXERCISE_VIDEOS = ${JSON.stringify(sorted, null, 0)};
`);

console.log(`\ncleared ${cleared} curated ids; generated map now holds ${Object.keys(kept).length}.`);
console.log('Those exercises now fall back to the "Watch a tutorial" search card.');
